### ISSUE TITLE
[Design] 보관함 상세 화면 추가

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DailyChallenge#26]
## 작업 내용

- 보관함 상세 화면을 추가

## Task

- [ ] 세그먼트 컨트롤러 추가
- [ ]  통계 부분은 통계 view를 재활용하기
- [ ]  메모 부분은 메모 view를 만들어서 추가
