### ISSUE TITLE
[Design] 유저 메시지 터치 액션

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DailyChallenge#8]
## 작업 내용

- 유저 메시지 레이블 터치했을 때 키보드가 올라오고 입력창이 표시되도록 합니다
- 리턴키를 누르면 키보드가 내려가고 메시지가 유저 메시지 레이블에 표시되도록 합니다

## Task

- [x] 키보드 표시
- [x] 입력창 표시
- [x] 빈화면 터치피 키보드 표시 해제
- [x] 리턴키 입력시 키보드 표시 해제
- [x] 리턴키 입력시 유저 메시지 레이블에 메시지 표시
